Ejercicios RubyMine/CRUD_Genero/config/routes.rb
Rails.application.routes.draw do
  resources :generos
  root 'generos#index'
end

Ejercicios RubyMine/CRUD_Genero/app/models/genero.rb
class Genero < ActiveRecord::Base
  validates :nombre,presence: true,length: {minimum: 5}
  validates :descripcion,presence: true
end

Ejercicios RubyMine/CRUD_Genero/app/controllers/generos_controller.rb
class GenerosController < ApplicationController

  def new
    @genero = Genero.new
  end

  def create
    @genero = Genero.new(genero_params)
      if @genero.save
        redirect_to @genero
      else
        render 'new'
      end
    end

  def edit
    @genero = Genero.find(params[:id])

  end

  def update
    @genero = Genero.find(params[:id])
    if @genero.update(genero_params)
      redirect_to @genero
    else
      render 'edit'
    end
  end

  def destroy
    @genero = Genero.find(params[:id])
    @genero.destroy
    redirect_to generos_url
  end

  def show
    @genero = Genero.find(params[:id])
  end

  def index
    @generos = Genero.all
  end

  private
     def genero_params
      params.require(:genero).permit(:nombre, :descripcion)
    end
end

Ejercicios RubyMine/CRUD_Genero/app/helpers/generos_helper.rb
module GenerosHelper
end

Ejercicios RubyMine/CRUD_Genero/app/views/generos/_form.html.erb
<%= form_for :genero do |f| %>
  <% if @genero.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@genero.errors.count, 'error') %>
        Los errores son:
      </h2>
      <ul>
        <% @genero.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :nombre %><br/>
    <%= f.text_field :nombre %><br/>
  </p>
  <p>
    <%= f.label :descripcion %><br>
    <%= f.text_field :descripcion %><br/>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

Ejercicios RubyMine/CRUD_Genero/app/views/generos/edit.html.erb
<h1>Ediccion del Genero Seleccionado</h1>

<%= form_for :genero,url: genero_path(@genero),method: :patch do |f| %>
    <% if @genero.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@genero.errors.count, 'error') %>
            No se puede editar el genero por los siguientes errores:
          </h2>
          <ul>
            <% @genero.errors.full_messages.each do |msg| %>
                <li> <%= msg %> </li>
            <% end%>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :nombre %><br/>
      <%= f.text_field :nombre %><br/>
    </p>
    <p>
      <%= f.label :descripcion %><br>
      <%= f.text_field :descripcion %><br/>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>
<p>
  <%= link_to 'Cancelar', new_genero_path%>
</p>

Ejercicios RubyMine/CRUD_Genero/app/views/generos/index.html.erb
<h1>Listado de Generos</h1>

<br>
<%= link_to 'Nuevo Genero', new_genero_path %>

<table border="1">
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th colspan="3">Acciones</th>
    </tr>
  <tbody>
    <% @generos.each do |genero| %>
      <tr>
        <td><%= genero.nombre %></td>
        <td><%= genero.descripcion %></td>
        <td><%= link_to 'Mostrar', genero %></td>
        <td><%= link_to 'Editar', edit_genero_path(genero) %></td>
        <td><%= link_to 'Eliminar', genero, method: :delete, data: { confirm: '¿Esta seguro de eliminar este Genero?' } %></td>
      </tr>
    <% end %>
</table>

Ejercicios RubyMine/CRUD_Genero/app/views/generos/new.html.erb
<h1>Nuevo Genero</h1>

<%= form_for :genero,url: generos_path do |f| %>
    <% if @genero.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@genero.errors.count, 'error') %>
            No se puede crear el genero por los siguientes errores:
          </h2>
          <ul>
            <% @genero.errors.full_messages.each do |msg| %>
                <li> <%= msg %> </li>
            <% end%>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :nombre %><br/>
      <%= f.text_field :nombre %><br/>
    </p>
    <p>
      <%= f.label :descripcion %><br>
      <%= f.text_field :descripcion %><br/>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>
<p>
  <%= link_to 'Cancelar', new_genero_path%>
</p>

Ejercicios RubyMine/CRUD_Genero/app/views/generos/show.html.erb
<p>Este es el genero seleccionado:</p>
<p>
  <strong>Nombre:</strong>
  <%= @genero.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @genero.descripcion %>
</p>

<%= link_to 'Editar', edit_genero_path(@genero) %> |
<%= link_to 'Atras', generos_path %>